---
alerting_dir: /opt/alerting
alertmanager_version: "0.27.0"

# Slack notifications
slack_enabled: true
slack_webhook_url: "{{ vault_slack_webhook_url }}"
slack_channel: "{{ vault_slack_channel }}"

# Email notifications
email_enabled: true
smtp_host: "{{ vault_smtp_host }}"
smtp_port: "{{ vault_smtp_port }}"
smtp_user: "{{ vault_smtp_user }}"
smtp_password: "{{ vault_smtp_password }}"
alert_email_from: "{{ vault_alert_email_from }}"
alert_email_to: "{{ vault_alert_email_to }}"

docker_network_name: traefik-public
