---
traefik_version: "3.1"
traefik_dir: /opt/traefik
traefik_acme_email: "{{ vault_acme_email }}"
traefik_dashboard_enabled: true
traefik_dashboard_domain: "traefik.{{ base_domain }}"
traefik_dashboard_user: "{{ vault_traefik_dashboard_user }}"
traefik_dashboard_password: "{{ vault_traefik_dashboard_password }}"
traefik_log_level: INFO
docker_network_name: traefik-public
