---
all:
  children:
    servers:
      hosts:
        vps-staging:
          ansible_host: "{{ vault_server_ip }}"
          ansible_port: "{{ vault_initial_ssh_port }}"
          ansible_user: "{{ vault_initial_user }}"
          server_hostname: srv-staging-01
