---
- name: restart sshd
  ansible.builtin.service:
    name: "{{ 'ssh' if ansible_distribution == 'Ubuntu' else 'sshd' }}"
    state: restarted

- name: restart ufw
  ansible.builtin.service:
    name: ufw
    state: restarted
