---
- name: Include system tasks
  ansible.builtin.import_tasks: system.yml

- name: Include user tasks
  ansible.builtin.import_tasks: users.yml

- name: Include SSH hardening tasks
  ansible.builtin.import_tasks: ssh.yml

- name: Include firewall tasks
  ansible.builtin.import_tasks: firewall.yml

- name: Include swap tasks
  ansible.builtin.import_tasks: swap.yml
