---
all:
  children:
    servers:
      hosts:
        vps-prod:
          ansible_host: "{{ vault_server_ip }}"
          ansible_port: "{{ vault_new_ssh_port }}"
          ansible_user: "{{ vault_new_user }}"
          server_hostname: srv-prod-01
