---
- name: Remove old Docker packages
  ansible.builtin.apt:
    name:
      - docker
      - docker-engine
      - docker.io
      - containerd
      - runc
    state: absent
    purge: true

- name: Install prerequisites for Docker repository
  ansible.builtin.apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
    state: present
    update_cache: true

- name: Add Docker GPG key
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg
    keyring: /etc/apt/keyrings/docker.gpg
    state: present

- name: Add Docker apt repository
  ansible.builtin.apt_repository:
    repo: >-
      deb [arch={{ ansible_architecture | replace('x86_64', 'amd64') }}
      signed-by=/etc/apt/keyrings/docker.gpg]
      https://download.docker.com/linux/{{ ansible_distribution | lower }}
      {{ ansible_distribution_release }} stable
    filename: docker
    state: present
    update_cache: true

- name: Install Docker CE packages
  ansible.builtin.apt:
    name:
      - docker-ce=5:27.5.1-1~ubuntu.24.04~noble
      - docker-ce-cli=5:27.5.1-1~ubuntu.24.04~noble
      - containerd.io
      - docker-compose-plugin
    state: present
    allow_downgrade: true
    update_cache: true

- name: Start and enable Docker service
  ansible.builtin.systemd:
    name: docker
    state: started
    enabled: true
