---
all:
  children:
    servers:
      hosts:
        vps-local:
          ansible_host: "172.16.3.138"
          ansible_user: "deploy"
          ansible_port: 2222
          server_hostname: ubuntu-vm
